name: Docker Builder CI

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]

# https://github.com/docker/build-push-action
jobs:

  # https://github.com/docker/build-push-action/issues/225
  docker:
    name: "Build Docker image develop"
    runs-on: ubuntu-latest #self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v3.3.0
      with:
        images: nanosaur/nanosaur_base
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=ref,event=tag
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1.10.0 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.6.1
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Docker inputs digest
      run: |
        echo ${{ steps.docker_build.outputs.digest }}
        echo ${{ steps.meta.outputs.tags }}
        
  # https://github.com/peter-evans/dockerhub-description
  update_docker_description:
    name: Update docker description
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: nanosaur/nanosaur
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.md
